"""remove delete-orphan

Revision ID: 0ca595f7bdd4
Revises: b45c4cd7a8f4
Create Date: 2025-02-10 15:54:09.601370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca595f7bdd4'
down_revision: Union[str, None] = 'b45c4cd7a8f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
