"""Fix back_populates mismatch

Revision ID: 0d41d93733a2
Revises: 94e257aa1366
Create Date: 2025-02-10 16:04:34.924964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d41d93733a2'
down_revision: Union[str, None] = '94e257aa1366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
