"""Fix back_populates mismatch

Revision ID: 8d650f5df0c8
Revises: e859c1bc231e
Create Date: 2025-02-10 16:10:06.722487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d650f5df0c8'
down_revision: Union[str, None] = 'e859c1bc231e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
