"""Fix delete-orphan issue in ProductSubOption

Revision ID: 94e257aa1366
Revises: 96ca1e62653b
Create Date: 2025-02-10 16:02:21.301347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94e257aa1366'
down_revision: Union[str, None] = '96ca1e62653b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
