"""remove delete-orphan

Revision ID: 96ca1e62653b
Revises: 0ca595f7bdd4
Create Date: 2025-02-10 15:58:36.232219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ca1e62653b'
down_revision: Union[str, None] = '0ca595f7bdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
