"""apply on delete and on update casecade

Revision ID: 980af7fb7250
Revises: c452ad66d837
Create Date: 2025-02-10 15:00:49.808593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '980af7fb7250'
down_revision: Union[str, None] = 'c452ad66d837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('features_product_ibfk_1', 'features_product', type_='foreignkey')
    op.drop_constraint('features_product_ibfk_2', 'features_product', type_='foreignkey')
    op.create_foreign_key(None, 'features_product', 'product_options', ['product_option_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'features_product', 'product_sub_options', ['product_sub_option_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('product_options_ibfk_1', 'product_options', type_='foreignkey')
    op.create_foreign_key(None, 'product_options', 'product_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_sub_options_ibfk_1', 'product_sub_options', type_='foreignkey')
    op.create_foreign_key(None, 'product_sub_options', 'product_options', ['ProductOption_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_sub_options', type_='foreignkey')
    op.create_foreign_key('product_sub_options_ibfk_1', 'product_sub_options', 'product_options', ['ProductOption_id'], ['id'])
    op.drop_constraint(None, 'product_options', type_='foreignkey')
    op.create_foreign_key('product_options_ibfk_1', 'product_options', 'product_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'features_product', type_='foreignkey')
    op.drop_constraint(None, 'features_product', type_='foreignkey')
    op.create_foreign_key('features_product_ibfk_2', 'features_product', 'product_sub_options', ['product_sub_option_id'], ['id'])
    op.create_foreign_key('features_product_ibfk_1', 'features_product', 'product_options', ['product_option_id'], ['id'])
    # ### end Alembic commands ###
