"""Fix back_populates mismatch

Revision ID: a86d8f0a82ab
Revises: 5383adf1334e
Create Date: 2025-02-10 16:16:46.539320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a86d8f0a82ab'
down_revision: Union[str, None] = '5383adf1334e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sub_options', sa.Column('product_option_id', sa.Integer(), nullable=False))
    op.drop_constraint('product_sub_options_ibfk_1', 'product_sub_options', type_='foreignkey')
    op.create_foreign_key(None, 'product_sub_options', 'product_options', ['product_option_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('product_sub_options', 'ProductOption_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_sub_options', sa.Column('ProductOption_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_sub_options', type_='foreignkey')
    op.create_foreign_key('product_sub_options_ibfk_1', 'product_sub_options', 'product_options', ['ProductOption_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('product_sub_options', 'product_option_id')
    # ### end Alembic commands ###
