"""apply on delete and on update casecade

Revision ID: b35b08e6c666
Revises: 980af7fb7250
Create Date: 2025-02-10 15:03:00.241181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35b08e6c666'
down_revision: Union[str, None] = '980af7fb7250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_options_ibfk_1', 'product_options', type_='foreignkey')
    op.create_foreign_key(None, 'product_options', 'product_categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_options', type_='foreignkey')
    op.create_foreign_key('product_options_ibfk_1', 'product_options', 'product_categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
