"""remove delete-orphan

Revision ID: b45c4cd7a8f4
Revises: cd3b1136af89
Create Date: 2025-02-10 15:52:51.502594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45c4cd7a8f4'
down_revision: Union[str, None] = 'cd3b1136af89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
