"""casecade apply

Revision ID: bac6a59270ec
Revises: fd0828eadec3
Create Date: 2025-02-10 16:59:57.338813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac6a59270ec'
down_revision: Union[str, None] = 'fd0828eadec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('features_product_ibfk_1', 'features_product', type_='foreignkey')
    op.drop_constraint('features_product_ibfk_2', 'features_product', type_='foreignkey')
    op.create_foreign_key(None, 'features_product', 'product_options', ['product_option_id'], ['id'])
    op.create_foreign_key(None, 'features_product', 'product_sub_options', ['product_sub_option_id'], ['id'])
    op.drop_constraint('product_sub_options_ibfk_1', 'product_sub_options', type_='foreignkey')
    op.create_foreign_key(None, 'product_sub_options', 'product_options', ['product_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_sub_options', type_='foreignkey')
    op.create_foreign_key('product_sub_options_ibfk_1', 'product_sub_options', 'product_options', ['product_option_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'features_product', type_='foreignkey')
    op.drop_constraint(None, 'features_product', type_='foreignkey')
    op.create_foreign_key('features_product_ibfk_2', 'features_product', 'product_sub_options', ['product_sub_option_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('features_product_ibfk_1', 'features_product', 'product_options', ['product_option_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
