"""create tables

Revision ID: c452ad66d837
Revises: 
Create Date: 2025-02-10 11:31:29.193686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c452ad66d837'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_category_name', sa.String(length=255), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('starting_price', sa.Double(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('tittle', sa.String(length=255), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('selection_type', sa.String(length=255), nullable=False),
    sa.Column('starting_price', sa.Double(), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('offer_price', sa.Double(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('max_deployment', sa.Integer(), nullable=False),
    sa.Column('max_indicator_access', sa.Integer(), nullable=False),
    sa.Column('max_signal_access', sa.Integer(), nullable=False),
    sa.Column('max_brokers', sa.Integer(), nullable=False),
    sa.Column('max_webhook_strategies', sa.Integer(), nullable=False),
    sa.Column('max_alerts_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_sub_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProductOption_id', sa.Integer(), nullable=False),
    sa.Column('sub_product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('selection_type', sa.String(length=255), nullable=False),
    sa.Column('starting_price', sa.Double(), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('tag', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['ProductOption_id'], ['product_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_option_id', sa.Integer(), nullable=False),
    sa.Column('product_sub_option_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('products', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['product_option_id'], ['product_options.id'], ),
    sa.ForeignKeyConstraint(['product_sub_option_id'], ['product_sub_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_option_id', 'features_product', ['product_option_id'], unique=False)
    op.create_index('idx_product_sub_option_id', 'features_product', ['product_sub_option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_sub_option_id', table_name='features_product')
    op.drop_index('idx_product_option_id', table_name='features_product')
    op.drop_table('features_product')
    op.drop_table('product_sub_options')
    op.drop_table('product_options')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
