"""rename column

Revision ID: d42990a8ad57
Revises: a86d8f0a82ab
Create Date: 2025-02-10 16:47:42.484115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd42990a8ad57'
down_revision: Union[str, None] = 'a86d8f0a82ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_options', 'tittle',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('product_options', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_options', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('product_options', 'tittle',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
