"""Fix back_populates mismatch

Revision ID: e859c1bc231e
Revises: 0d41d93733a2
Create Date: 2025-02-10 16:07:57.071708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e859c1bc231e'
down_revision: Union[str, None] = '0d41d93733a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
