"""casecade apply

Revision ID: fd0828eadec3
Revises: 64cae4b10e4a
Create Date: 2025-02-10 16:58:38.542999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0828eadec3'
down_revision: Union[str, None] = '64cae4b10e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_options_ibfk_1', 'product_options', type_='foreignkey')
    op.create_foreign_key(None, 'product_options', 'product_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_options', type_='foreignkey')
    op.create_foreign_key('product_options_ibfk_1', 'product_options', 'product_categories', ['category_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
